[package]
name = "hackerrank-solutions"
version = "0.1.0"
authors = ["ciuncan <ceyhuncanu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
